version: '3.2'

services:
  feedback-service:
    build: feedback-service
    ports:
      - 20080:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./feedback-service:/app
    depends_on:
      - mysql
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: verysecret
      MYSQL_DATABASE: feedback
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
